all:
  hosts:
    ipa.otus.lan:
      ansible_host: 192.168.11.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/server/virtualbox/private_key
    client1.otus.lan:
      ansible_host: 192.168.11.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/client1/virtualbox/private_key
    client2.otus.lan:
      ansible_host: 192.168.11.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/client2/virtualbox/private_key
ipaserver:
  hosts:
    ipa.otus.lan:
  vars:
    ipaadmin_password: ADMPassword1
    ipadm_password: DMPassword1
    ipaserver_domain: otus.lan
    ipaserver_realm: OTUS.LAN
    ipaserver_no_host_dns: true
    ipaserver_hostname: ipa.otus.lan
    ipaserver_setup_dns: true
    ipaserver_no_forwarders: true
ipaclients:
  hosts:
    client1.otus.lan:
    client2.otus.lan:
  vars:
    ipaadmin_password: ADMPassword1
    ipaserver_hostname: ipa.otus.lan
    ipaserver_domain: otus.lan
    ipaserver_realm: OTUS.LAN